openapi: 3.0.4
info:
  title: Currency Symbols
  description: Currency Symbols is a simple tool for getting currency symbols. It returns the currency symbol, name, and more of a currency.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/currencysymbols:
    get:
      summary: Get Currency Symbol
      description: Currency Symbols is a simple tool for getting currency symbols. It returns the currency symbol, name, and more of a currency.
      operationId: currencysymbols
      parameters:
      - name: currency
        in: query
        schema:
          type: string
        required: true
        description: The currency code for which you want to get the symbol (e.g., USD)
        example: USD
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  countriesFound:
                  - country_name: AMERICAN SAMOA
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: BONAIRE, SINT EUSTATIUS AND SABA
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: BRITISH INDIAN OCEAN TERRITORY (THE)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: ECUADOR
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: EL SALVADOR
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: GUAM
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: HAITI
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: MARSHALL ISLANDS (THE)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: MICRONESIA (FEDERATED STATES OF)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: NORTHERN MARIANA ISLANDS (THE)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: PALAU
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: PANAMA
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: PUERTO RICO
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: TIMOR-LESTE
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: TURKS AND CAICOS ISLANDS (THE)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: UNITED STATES MINOR OUTLYING ISLANDS (THE)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: UNITED STATES OF AMERICA (THE)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: VIRGIN ISLANDS (BRITISH)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  - country_name: VIRGIN ISLANDS (U.S.)
                    currency_name: US Dollar
                    currency_iso_code: USD
                    currency_number: '840'
                    currency_mnr_unts: '2'
                    currency_symbol: $
                  currency: USD
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
